### Site Settings ###
title: Welcome to my portfolio!
description: >
  I turn coffee â˜• into code, use tabs over spaces, and never broke production.
baseurl: ""
remote_theme: yousinix/portfolYOU@v1.0.0
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji
  - jekyll-remote-theme



### Navbar Settings ###
# nav_exclude:                                            # The following paths are excluded from navbar
#  - pages/tags.html
#  - pages/404.html
#  - pages/index.md


### Author Info ###
author:
  name              : Jyothi Guruprasad
  image             : https://i.imgur.com/uyDNQnn.jpg
  behance           : your_username
# dribbble          : your_username
  email             : vinjyothi14@gmail.com
  facebook          : your_username
  github            : jyothi1721
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : jyothi-guruprasad
  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
# permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
# disqus:
  # shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
# analytics:
 # enabled: true                                        # Set true to enable analytics
  # google:
    # tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
# buymeacoffee:
  # enabled: false
  # username: your_username
  # color: "#007bff"
  # message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  # description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
